language: node_js
node_js:
  - '0.12'

sudo: false
cache:
  directories:
    - node_modules
    - jspm_packages

env:
  global:
    - secure: c761LnJULD8JYkuZWwN6zWKGt/4FY8RZKE1/xpeEDE95STrc4JGrvKimBDhtHGuvduBvJNUD457TP/NKCeT58wWv7uu7P879dDLy3oLeZUOmxisf/JHYQ2kXMmuxsyo5cU8D6fTLMAkR2RO+fWQTa1mKHHUlqgJpM322TnyvP6XhXl/bapYDiWWq9Vsk73twVt0U58Sln+qvVPtfRImhCbG6+c80s46k/V29nh129XvgeGqMt/d0IyQOPj68GLVa2JlnH5YeUHLSSLceWEv7tLCbfLCW0SbX3xq2PzDbKD4xL0yoAX1DBEGWPg4YSFnX3ogzAuq582oUircelN9y1pvavpLkToB0bx7UWiZR+Rll0WGmWXxkSljjkja85Jm+0ZGDjyc/1MEnVBd11DmqiVLrDrpXIOajVTG0FbwsKuJ7bHoXzustjTYcUIv0qdPDVE1WDoyvNm6WH1EHFGMUMFObbF53vkD/vgKbeev+C0gVGAJSARAFzi7szGz0rDG0yIEkNDJnfPJ+dka21OOCyFXjWDOyIkZoQHDgUOd/SFuyXPFvm+QydKcLMqbu7oBH8QEQkFuYZu0LcKYWt6EtiMycQbgfLwr9TGe9HGLdARFPVtMciZ2al4sODQC0kPR8MU84qD0XIeYk910dYtC7uDY5lTydGY17TQQX7PVjdfM=
    - secure: lQrhZurBpq+YZa3gg8gOC6wAgEV33eBhVvRhr7kxXyhvZ85rYuWPcBtU3G2uuWvxeJo3PoTgozP/M/mGI/jFTEbSi/X3IFhLZSjPYTN53D1tsUSZ/H4hd2S7xaJLZCUcj2iOzuMBKv5FhvfJK3JTWQ7FeDZt8tiz7G9NRuRpxvOMwZBCHFugAyYXjJOke5pQsPyozCxJGfkHsLe/lUGFVjpwIAlnJ46KHkgU9pcF+atcOhpmsLlLsHcgHIju80D1m7x+tajvrev8ZNN3HUk/PfotjPVYVPXBxB81BioQXY0LJ/uOdpdEOy6hf2pNEraT/yODt+dXAH7pqAOKVS4UU0YIEGsDntG/J3URLSDjghd8isWZbViE8QcKTrF50DZXj+vkn7m0gHKAmVt+EruptEZRZoj8F6i3f23SOqrraH1louAJ9VIdpxVD8UX3cLlBx4R600Ab/z0yEXQ4OajGc4oB8Gqt9rds7dOJDgkjUkgOE74C9L7/bz3HL9+45JcFdC2m9cAgaP/skbEijvLGmPwgyiQDZvE/KKgqh+7bYxlabWy5LE8YATjPadrufHCa67NWdt28iZnkwEMbjRj91L6CU6+/XN3AsbglNAoS0AkPwUMwJJ5NQoLVXDpnql2LYRNhMmHblUW9RAqoZWPYt9NRZjJ0Uc+SpGMomO+Ye3c=
    - secure: bmkhrU/S7kTajJWz6wPgvi0ME9ZmxaNOxcRG1W38kepYg5qj5+Rp/UTpWzZGX9icPKRXTNtkWVhg63xRCiWkXuMgoemvEdq2ecakGMHMO3c0TybCcsgJAN/top1UIcBJHoOpmtyr2IQMJ3vLfG/yxb9nD312pIvenTSpGHwZnH2rh1nXf3XkntOBrN2sDBIalcuCw2zo2i7o9cKSmrNS5FRAZ2WJNFnZWB4LdIrU1+dQFnCB8MD8fwSOjDSG1ZTCuVfFSk4NKicOKwTYNBiTGAgIcX50Ncal1kG/AV4O3s4qnBH1eDA782jk+dgQjwo+XybA7Pp5pP5nIqIHa9pyhxAg/LA+J1I8x7M8fna76Ah7qOC7YT1yD99ED/G4VLsZv4R5FuLjnUU3KH13fVLvsYxtQGY82FEoxlG81V0I2PgILx1PPvmkOEDJRVc4nnKWpeVOgOYX4YIWPzFxBO0DLDq9UCMt0+f3ncWqRdvt7xgzv37iFDGDdUADnt+d+pK8rMxNp31gVaKWN1muRKmQEfFsJXALnCY/D/wGxGRZoA60b1AXwzwApQ5c7TGmEtGUqbfc+yHDOKcrPsLwRPRlUJR6tWWseLDYqY4UX+CvUpiK/Ih5C5xCWIIeL+wXxUZtxii3aF06QMk2RPtAbvsFFj6Ly6apy3mwzgqVsblNFs4=

before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_AUTH

addons:
  sauce_connect: true
